# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - agl-challenge

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

    - name: Run unit tests
        run: python -m pytest --import-mode=append tests/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://aglacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1a56827b05ad4c6293a6cbacbbd2ff4b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8aaf8c670963417683978ed1b9342582 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: aglacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1a56827b05ad4c6293a6cbacbbd2ff4b }}/eglmlchallenge:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'agl-challenge'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d46ce3f948bd40748672e171337c0cff }}
        images: 'aglacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1a56827b05ad4c6293a6cbacbbd2ff4b }}/eglmlchallenge:${{ github.sha }}'